spring.application.name=api-questify
server.servlet.context-path=/questify
spring.mvc.static-path-pattern=/static/**

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.use-root-path=true
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.maximum-pool-size=10

app.swagger.server-url=${APP_SWAGGER_SERVER_URL}

spring.ai.vertex.ai.gemini.project-id=new-spring-487415
spring.ai.vertex.ai.gemini.location=us-east4
spring.ai.vertex.ai.gemini.model=gemini-1.5-flash